import { Invoice } from '../../models/Invoice';
import { BillPayee } from '../../models/BillPayee';

export const dummydata: Invoice[] = [
    new Invoice({
        invoiceId: 1,
        companyId: "Bell Canada",
        billPayeeId: 101,
        providerId: "Provider1",
        subtotal: 100,
        tax: 20,
        discount: 10,
        total: 150,
        amountDue: 150,
        amountPaid: 0,
        dateCreated: new Date(2024, 8, 9),
        dateUpdated: new Date(2024, 8, 9),
        status: "D",
        currency: "USD",
        extInvoiceID: "ext123",
        invoiceReference: "Ref001",
        userNumber: "User001",
        createdBy: "Admin",
        updatedBy: "Admin",
        extUserID: "extUser001",
        memo: "Monthly invoice",
        note: "Pay by due date",
        selected: false
    }),
    new Invoice({
        invoiceId: 2,
        companyId: "Bell Canada",
        billPayeeId: 102,
        providerId: "Provider1",
        subtotal: 100,
        tax: 20,
        discount: 10,
        total: 150,
        amountDue: 150,
        amountPaid: 0,
        dateCreated: new Date(2024, 8, 9),
        dateUpdated: new Date(2024, 8, 9),
        status: "D",
        currency: "USD",
        extInvoiceID: "ext124",
        invoiceReference: "Ref002",
        userNumber: "User002",
        createdBy: "Admin",
        updatedBy: "Admin",
        extUserID: "extUser002",
        memo: "Monthly invoice",
        note: "Pay by due date",
        selected: false
    }),
    new Invoice({
        invoiceId: 3,
        companyId: "Bell Canada",
        billPayeeId: 103,
        providerId: "Provider1",
        subtotal: 100,
        tax: 20,
        discount: 10,
        total: 150,
        amountDue: 150,
        amountPaid: 0,
        dateCreated: new Date(2024, 8, 9),
        dateUpdated: new Date(2024, 8, 9),
        status: "D",
        currency: "USD",
        extInvoiceID: "ext125",
        invoiceReference: "Ref003",
        userNumber: "User003",
        createdBy: "Admin",
        updatedBy: "Admin",
        extUserID: "extUser003",
        memo: "Monthly invoice",
        note: "Pay by due date",
        selected: false
    })
];



export const dummydataPayees: BillPayee[] = [
    new BillPayee({
        billPayeeId: 101,
        contactId: "Bell Ecuador",
        bankNumber: "123456",
        branchNumber: "789",
        accountNumber: "987654321",
        peCompanyId: "PE001",
        clientId: "CLIENT001",
        createdBy: "User123",
        updatedBy: "User123",
        extCompanyId: "EXTCOMP001",
        createdByContact: "ContactPerson",
        providerId: "PROV001",
        status: "Active",
        dateCreated: new Date(2024, 8, 9),
        dateUpdated: new Date(2024, 8, 9),
    }),
    new BillPayee({
        billPayeeId: 102,
        contactId: "Bell USA",
        bankNumber: "654321",
        branchNumber: "123",
        accountNumber: "123456789",
        peCompanyId: "PE002",
        clientId: "CLIENT002",
        createdBy: "User456",
        updatedBy: "User456",
        extCompanyId: "EXTCOMP002",
        createdByContact: "AnotherContactPerson",
        providerId: "PROV002",
        status: "Inactive",
        dateCreated: new Date(2024, 8, 9),
        dateUpdated: new Date(2024, 8, 9),
    }),
    new BillPayee({
        billPayeeId: 103,
        contactId: "Bell Canada",
        bankNumber: "654321",
        branchNumber: "123",
        accountNumber: "123456789",
        peCompanyId: "PE002",
        clientId: "CLIENT002",
        createdBy: "User456",
        updatedBy: "User456",
        extCompanyId: "EXTCOMP002",
        createdByContact: "AnotherContactPerson",
        providerId: "PROV002",
        status: "Inactive",
        dateCreated: new Date(2024, 8, 9),
        dateUpdated: new Date(2024, 8, 9),
    })
];
